'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslint-cache --fix'
  - 'prettier --log-level warn --cache --write'
'*.{json,yml,scss}': 'prettier --loglevel warn --cache --write'
